[package]
name = "cross-hello"
version = "0.1.0"
edition = "2021"

[dependencies]
rppal = "0.14.1"
anyhow = "1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
