[package]
name = "vahana"
version = "0.1.0"
edition = "2021"

[lib]
name = "vahana"
crate-type = ["cdylib", "rlib"]

[dependencies]
rppal = "0.14.1"
anyhow = "1.0"
pyo3 = { version = "0.18.3", features = ["extension-module", "anyhow"] }
